apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: media-download
    name: media-download
  name: media-download
spec:
  selector:
    matchLabels:
      app: media-download
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: media-download
    spec:
      containers:
        - image: "reecerussell/open-social-media-download"
          name: media-download
          resources:
            limits:
              cpu: "100m"
              memory: "200Mi"
            requests:
              cpu: "20m"
              memory: "50Mi"
          ports:
            - containerPort: 9292
              protocol: TCP
          env:
            - name: MEDIA_API_URL
              value: http://media
          livenessProbe:
            httpGet:
              path: /health
              port: 9292
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 9292
            initialDelaySeconds: 3
            periodSeconds: 3