version: "3.7"

networks:
    open-social:
        driver: bridge

services:
    ingress:
        image: nginx
        volumes:
            - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
        ports:
            - 80:80
        networks:
            - open-social
        depends_on:
            - backend
            - media-download

    backend:
        image: reecerussell/open-social-backend
        build:
            context: .
            dockerfile: ./service/backend/Dockerfile
        environment:
            USERS_API_URL: http://users:80
            AUTH_API_URL: http://auth:80
            POSTS_API_URL: http://posts:80
            MEDIA_API_URL: http://media:80
            TOKEN_PUBLIC_KEY: /app/token-rsa.dev.pub
        volumes:
            - ./token-rsa.dev.pub:/app/token-rsa.dev.pub
        networks:
            - open-social
        depends_on:
            - users
            - auth
            - posts
            - media

    users:
        image: reecerussell/open-social-users
        build:
            context: .
            dockerfile: ./service/users/Dockerfile
        environment:
            CONNECTION_STRING: ${CONNECTION_STRING}
        networks:
            - open-social

    auth:
        image: reecerussell/open-social-auth
        build:
            context: .
            dockerfile: ./service/auth/Dockerfile
        environment:
            USERS_API_URL: http://users:80
            TOKEN_PRIVATE_KEY: /app/token-rsa.dev.pem
        volumes:
            - ./token-rsa.dev.pem:/app/token-rsa.dev.pem
        networks:
            - open-social
        depends_on:
            - users

    posts:
        image: reecerussell/open-social-posts
        build:
            context: .
            dockerfile: ./service/posts/Dockerfile
        environment:
            CONNECTION_STRING: ${CONNECTION_STRING}
            USERS_API_URL: http://users:80
        networks:
            - open-social
        depends_on:
            - users

    media:
        image: reecerussell/open-social-media
        build:
            context: .
            dockerfile: ./service/media/Dockerfile
        environment:
            CONNECTION_STRING: ${CONNECTION_STRING}
            MEDIA_BUCKET: open-social-media
            GOOGLE_APPLICATION_CREDENTIALS: /cred/media-account.json
        volumes:
            - ~/.gcp/media-account.json:/cred/media-account.json
        networks:
            - open-social

    media-download:
        image: reecerussell/open-social-media-download
        build:
            context: .
            dockerfile: ./cmd/media-download/Dockerfile
        environment:
            MEDIA_API_URL: http://media
        networks:
            - open-social
        depends_on:
            - media
