apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: posts
        name: posts
    name: posts
spec:
    selector:
        matchLabels:
            app: posts
    replicas: 1
    template:
        metadata:
            labels:
                app: posts
        spec:
            containers:
                - image: "reecerussell/open-social-posts"
                  name: posts
                  resources:
                      limits:
                          cpu: "200m"
                          memory: "400Mi"
                      requests:
                          cpu: "40m"
                          memory: "100Mi"
                  env:
                      - name: "CONNECTION_STRING"
                        valueFrom:
                            secretKeyRef:
                                name: database
                                key: connection-string
                  ports:
                      - containerPort: 80
                        protocol: TCP
                  livenessProbe:
                      httpGet:
                          path: /health
                          port: 80
                      initialDelaySeconds: 3
                      periodSeconds: 30
                      timeoutSeconds: 2
                  readinessProbe:
                      httpGet:
                          path: /health
                          port: 80
                      initialDelaySeconds: 3
                      periodSeconds: 30
                      timeoutSeconds: 2
