apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: posts
    name: posts
  name: posts
spec:
  selector:
    matchLabels:
      app: posts
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - image: "reecerussell/open-social-posts"
          name: posts
          resources:
            limits:
              cpu: "100m"
              memory: "200Mi"
            requests:
              cpu: "20m"
              memory: "50Mi"
          ports:
            - containerPort: 9292
              protocol: TCP
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: database
                  key: connection-string
            - name: USERS_API_URL
              value: http://users
          livenessProbe:
            httpGet:
              path: /health
              port: 9292
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 9292
            initialDelaySeconds: 3
            periodSeconds: 3
