apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: posts
spec:
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: posts