apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: backend
        name: backend
    name: backend
spec:
    selector:
        matchLabels:
            app: backend
    replicas: 1
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - image: "reecerussell/open-social-backend"
                  name: backend
                  resources:
                      limits:
                          cpu: "200m"
                          memory: "400Mi"
                      requests:
                          cpu: "40m"
                          memory: "100Mi"
                  env:
                      - name: "USERS_API_URL"
                        value: "http://users"
                  ports:
                      - containerPort: 80
                        protocol: TCP
                  livenessProbe:
                      httpGet:
                          path: /health
                          port: 80
                      initialDelaySeconds: 3
                      periodSeconds: 30
                      timeoutSeconds: 2
                  readinessProbe:
                      httpGet:
                          path: /health
                          port: 80
                      initialDelaySeconds: 3
                      periodSeconds: 30
                      timeoutSeconds: 2
