export const LOAD_PROFILE = "LOAD_PROFILE";
export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS";
export const LOAD_PROFILE_ERROR = "LOAD_PROFILE_ERROR";

export const FOLLOW_PROFILE = "FOLLOW_PROFILE";
export const FOLLOW_PROFILE_SUCCESS = "FOLLOW_PROFILE_SUCCESS";
export const FOLLOW_PROFILE_ERROR = "FOLLOW_PROFILE_ERROR";

export const UNFOLLOW_PROFILE = "UNFOLLOW_PROFILE";
export const UNFOLLOW_PROFILE_SUCCESS = "UNFOLLOW_PROFILE_SUCCESS";
export const UNFOLLOW_PROFILE_ERROR = "UNFOLLOW_PROFILE_ERROR";
