apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: backend
        name: backend
    name: backend
spec:
    selector:
        matchLabels:
            app: backend
    replicas: 1
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - image: "reecerussell/open-social-users"
                  name: backend
                  resources:
                      limits:
                          cpu: "100m"
                          memory: "200Mi"
                      requests:
                          cpu: "20m"
                          memory: "50Mi"
                  ports:
                      - containerPort: 80
                        protocol: TCP
