apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: users
    name: users
  name: users
spec:
  selector:
    matchLabels:
      app: users
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - image: "reecerussell/open-social-users"
          name: users
          resources:
            limits:
              cpu: "100m"
              memory: "200Mi"
            requests:
              cpu: "20m"
              memory: "50Mi"
          ports:
            - containerPort: 9292
              protocol: TCP
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: database
                  key: connection-string
          livenessProbe:
            httpGet:
              path: /health
              port: 9292
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 9292
            initialDelaySeconds: 3
            periodSeconds: 3
