CREATE OR ALTER FUNCTION [dbo].[HasUserLikedPost] (@PostId INT, @UserId INT)
RETURNS BIT
BEGIN
	IF EXISTS(SELECT [PostId] FROM [PostLikes] WHERE [PostId] = @PostId AND [UserId] = @UserId)
	BEGIN
		RETURN CAST(1 AS BIT)
	END

	RETURN CAST(0 AS BIT)
END