CREATE TABLE [dbo].[Posts] (
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[ReferenceId] UNIQUEIDENTIFIER NOT NULL UNIQUE,
	[UserId] INT NOT NULL FOREIGN KEY REFERENCES [Users] ([Id]),
	[MediaId] INT NULL FOREIGN KEY REFERENCES [Media] ([Id]),
	[Posted] DATETIME NOT NULL,
	[Caption] NVARCHAR(255) NOT NULL
)