CREATE TABLE [Users] (
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[ReferenceId] UNIQUEIDENTIFIER NOT NULL,
	[MediaId] INT NULL FOREIGN KEY REFERENCES [Users] ([Id]),
	[Username] VARCHAR(20) NOT NULL UNIQUE,
	[PasswordHash] VARCHAR(MAX) NOT NULL,
	[Bio] VARCHAR(255) NOT NULL
)